### ISSUE TITLE
Jeff's concern about blinding factors

### ISSUE THREAD

**Issue by FredericJacobs** [chris-wood/draft-wood-cfrg-blind-signatures#69]
On the mailing list, Jeff says:

> We need a strong clarification that blinding factors should be rejection sampled from the RSA group, meaning same bit width and rejection if they exceed the modulus.  I’ve some GCD test in GNU Taler’s code but that’s unnecessary since n - phi(n) = pq - (p-1)(q-1) = p + q -1 << n. 
> 
> Implementations that produce produce blinding factors using floor(log_2 n) bits provide no appreciable anonymity.  It’s a trivial attack:  An exchange computes isig[i] / rsig[j] for all issued signatures isig[i] and all redeemed signatures rsig[j].  Anytime i and j correspond then isig[i] / rsig[j] gives a blinding factor, so if blinding factors leak half a bit of entropy, then the exchange deanonymizes the user after only a few spent coins, usually only one transaction.
> 
> Implementations that produce blinding factors using the PSS code deanonymize users with only one coin!  I’d say blinding factors are the most important part of the document.

I don't fully understand the claim. The blinding factors in the spec are defined as:
> r = random_integer_uniform(1, n)

which should alleviate Jeff's concern.

**Comment by FredericJacobs** [comment]
@burdges, can you clarify?

**Comment by burdges** [comment]
Yes, an integer selected uniformly mod n works fine, but people often mess this up.

**Comment by chris-wood** [comment]
Would it help if we added an appendix that describes how one might implement `random_integer_uniform`, i.e., either via rejection sampling or by taking @kwantam's suggestion and generating more bits than necessary before reducing mod n?

**Comment by burdges** [comment]
Yes, I'd emphasize that uniform mod n matters and mention the reduction trick suffices.

**Comment by chris-wood** [comment]
@FredericJacobs can we close this and fold it into #55?

**Comment by FredericJacobs** [comment]
Totally
